#!/usr/bin/env python
# -*- coding: utf-8 -*-
""" Ban an IP address with Fail2Ban using the Cloudflare v4 API
    Usage:   ./ban <cf_email> <cf_token> <ip>
"""

import sys
import CloudFlare
import CloudFlare.exceptions

def main(argv):
    cf_email = argv[1]
    cf_token = argv[2]
    ban_ip   = argv[3]

    cf = CloudFlare.CloudFlare(email=cf_email, token=cf_token)

    rule = {"mode": "block", "configuration": {"target": "ip", "value": ban_ip}}

    try:
        cf.user.firewall.access_rules.rules.post(data=rule)
    except CloudFlare.exceptions.CloudFlareAPIError as e:
        # Catch the exception and pass, to avoid fail2ban logging credentials
        pass

if __name__ == "__main__":
    exit(main(sys.argv))
